# -*- coding: utf-8 -*-
"""tests/test_feature_engineering.py29/7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pLFfPn-C4HrEkrzQcGhUUrx4OcvMvJmp
"""

"""
test_feature_engineering.py

Unit tests for the feature engineering module (feature_builder.py).
"""

import sys
import os
import pandas as pd

# Add the parent directory to the path so we can import the modules
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from feature_builder import extract_datetime_features, group_rare_categories


def test_extract_datetime_features():
    """Test that calendar features are correctly extracted from a datetime column."""
    df = pd.DataFrame({"date": ["2026-07-29", "2025-01-01", "2024-12-25"]})
    result = extract_datetime_features(df, "date", drop_original=True)

    expected_columns = [
        "date_year",
        "date_month",
        "date_day",
        "date_day_of_week",
        "date_quarter",
        "date_is_weekend"
    ]

    for col in expected_columns:
        assert col in result.columns, f"Column '{col}' should exist"

    assert "date" not in result.columns, "Original datetime column should be dropped"
    assert result["date_year"].tolist() == [2026, 2025, 2024]
    print("✅ test_extract_datetime_features passed")


def test_extract_datetime_features_keep_original():
    """Test that the original datetime column is kept when specified."""
    df = pd.DataFrame({"timestamp": ["2026-07-29"]})
    result = extract_datetime_features(df, "timestamp", drop_original=False)
    assert "timestamp" in result.columns, "Original column should be kept"
    assert "timestamp_year" in result.columns, "Derived column should exist"
    print("✅ test_extract_datetime_features_keep_original passed")


def test_group_rare_categories():
    """Test that rare categories are grouped into a single bucket."""
    df = pd.DataFrame({"cat": ["A"] * 90 + ["B"] * 5 + ["C"] * 5})
    result = group_rare_categories(df, "cat", threshold=0.05)

    unique_values = result["cat"].unique()
    assert len(unique_values) == 2, "Should have only 2 categories (A and rare)"
    assert "rare" in unique_values, "'rare' bucket should exist"
    assert result["cat"].value_counts()["rare"] == 10, "B and C should be grouped (5+5)"
    print("✅ test_group_rare_categories passed")


def test_group_rare_categories_low_cardinality():
    """Test that low-cardinality columns are not modified."""
    df = pd.DataFrame({"cat": ["A"] * 80 + ["B"] * 20})
    # Default threshold is 0.01, and min_unique is 10. Since unique count is 2 (<10), nothing changes.
    result = group_rare_categories(df, "cat")
    assert result["cat"].nunique() == 2, "Low cardinality column should remain unchanged"
    print("✅ test_group_rare_categories_low_cardinality passed")


def test_group_rare_categories_no_rare():
    """Test that no changes are made when no rare categories exist."""
    df = pd.DataFrame({"cat": ["A"] * 60 + ["B"] * 40})
    result = group_rare_categories(df, "cat", threshold=0.05)
    assert result["cat"].nunique() == 2, "No rare categories should be grouped"
    assert "rare" not in result["cat"].values, "'rare' bucket should not appear"
    print("✅ test_group_rare_categories_no_rare passed")


if __name__ == "__main__":
    test_extract_datetime_features()
    test_extract_datetime_features_keep_original()
    test_group_rare_categories()
    test_group_rare_categories_low_cardinality()
    test_group_rare_categories_no_rare()
    print("\n🎉 All feature engineering tests passed successfully!")