# -*- coding: utf-8 -*-
"""tests/test_pipeline.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hneGw2_tEASrL_Ev_3joCEVHW7qKIJHF
"""

"""
test_pipeline.py

Integration tests for the complete preprocessing pipeline.
"""

import sys
import os
import pandas as pd
import numpy as np

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from cleaner import PreprocessingPipeline, PreprocessingConfig


def test_pipeline_full_execution():
    """Test that the full pipeline runs without errors on a sample dataset."""
    # Create a sample dataset with various issues
    df = pd.DataFrame({
        'id': [1, 2, 3, 4, 5],
        'numeric_col': [1.0, 2.0, np.nan, 4.0, 100.0],  # missing + outlier
        'categorical_col': ['A', 'B', 'A', 'C', 'C'],
        'date_col': ['2026-01-01', '2026-01-02', '2026-01-03', '2026-01-04', '2026-01-05'],
        'target': [0, 1, 0, 1, 0]
    })

    # Exclude 'id' and 'target' from automatic processing (prevent target leakage)
    config = PreprocessingConfig(columns_to_exclude=['id', 'target'])
    pipeline = PreprocessingPipeline(config=config)

    result = pipeline.run(df)

    # Assertions
    assert result is not None, "Pipeline should return a DataFrame"
    assert not result.empty, "Result should not be empty"
    assert result.isnull().sum().sum() == 0, "Result should have no missing values"

    # Check that datetime features were created
    assert 'date_col_year' in result.columns, "Year feature should exist"
    assert 'date_col_month' in result.columns, "Month feature should exist"

    # Check that 'id' and 'target' are NOT in the result (they were excluded)
    assert 'id' not in result.columns, "Excluded column 'id' should not appear"
    assert 'target' not in result.columns, "Excluded column 'target' should not appear"

    print("✅ test_pipeline_full_execution passed!")


def test_pipeline_with_drop_strategy():
    """Test pipeline with explicit drop strategy for missing values."""
    df = pd.DataFrame({
        'A': [1, 2, np.nan, 4],
        'B': ['x', 'y', 'z', None]
    })

    # Use the spec-compliant simple functions, but test the pipeline
    config = PreprocessingConfig()
    pipeline = PreprocessingPipeline(config=config)

    result = pipeline.run(df)

    # The pipeline uses advanced logic, but should still run fine
    assert result.isnull().sum().sum() == 0, "Pipeline should handle missing values"
    print("✅ test_pipeline_with_drop_strategy passed!")


if __name__ == "__main__":
    test_pipeline_full_execution()
    test_pipeline_with_drop_strategy()
    print("\n🎉 All pipeline integration tests passed successfully!")