# -*- coding: utf-8 -*-
"""tests/test_preprocessing.py29/7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11S82ggVQ8tM7oJsK-cr95CXyI-tdRHdX
"""

"""
test_preprocessing.py

Unit tests for the preprocessing module (cleaner.py).
"""

import sys
import os
import pandas as pd

# Add the parent directory to the path so we can import the modules
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from cleaner import remove_duplicates, handle_missing_values


def test_remove_duplicates():
    """Test that duplicate rows are correctly removed."""
    df = pd.DataFrame({"A": [1, 1, 2], "B": ["x", "x", "y"]})
    result = remove_duplicates(df)
    assert len(result) == 2, "Should have removed 1 duplicate row"
    print("✅ test_remove_duplicates passed")


def test_handle_missing_values_mean():
    """Test mean imputation for numerical columns."""
    df = pd.DataFrame({"A": [1, None, 3], "B": ["a", "b", None]})
    result = handle_missing_values(df, strategy="mean")
    assert result["A"].isnull().sum() == 0, "Missing values should be filled"
    assert result["A"][1] == 2.0, "Mean of 1 and 3 should be 2.0"
    assert result["B"].isnull().sum() == 0, "Categorical missing should be filled with mode"
    print("✅ test_handle_missing_values_mean passed")


def test_handle_missing_values_median():
    """Test median imputation for numerical columns."""
    df = pd.DataFrame({"A": [1, 2, None, 100], "B": ["x", "y", "z", None]})
    result = handle_missing_values(df, strategy="median")
    assert result["A"].isnull().sum() == 0
    assert result["A"][2] == 2.0, "Median of [1, 2, 100] should be 2.0"
    print("✅ test_handle_missing_values_median passed")


def test_handle_missing_values_mode():
    """Test mode imputation for numerical columns."""
    df = pd.DataFrame({"A": [1, 1, 1, None, 2], "B": ["x", "x", "y", None, "y"]})
    result = handle_missing_values(df, strategy="mode")
    assert result["A"].isnull().sum() == 0
    assert result["A"][3] == 1.0, "Mode of A should be 1.0"
    assert result["B"].isnull().sum() == 0
    print("✅ test_handle_missing_values_mode passed")


def test_handle_missing_values_drop():
    """Test dropping rows with missing values."""
    df = pd.DataFrame({"A": [1, None, 3], "B": ["a", "b", "c"]})
    result = handle_missing_values(df, strategy="drop")
    assert len(result) == 2, "Row with NaN should be dropped"
    assert result["A"].isnull().sum() == 0
    print("✅ test_handle_missing_values_drop passed")


def test_handle_missing_values_invalid_strategy():
    """Test that an invalid strategy raises ValueError."""
    df = pd.DataFrame({"A": [1, 2, 3]})
    try:
        handle_missing_values(df, strategy="invalid")
        assert False, "Should have raised ValueError"
    except ValueError as e:
        assert "unsupported" in str(e).lower()
        print("✅ test_handle_missing_values_invalid_strategy passed")


if __name__ == "__main__":
    test_remove_duplicates()
    test_handle_missing_values_mean()
    test_handle_missing_values_median()
    test_handle_missing_values_mode()
    test_handle_missing_values_drop()
    test_handle_missing_values_invalid_strategy()
    print("\n🎉 All preprocessing tests passed successfully!")