# -*- coding: utf-8 -*-
"""clean29/7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1So01WstzpjBAQkUwa7tZ8gWbQma5zkUO
"""

"""
cleaner.py

Generic, production-ready tabular data preprocessing engine.

This module implements a complete preprocessing pipeline for ANY tabular
dataset, following Object-Oriented Programming and SOLID principles.

Pipeline execution order:
    Validation -> Cleaning -> Missing Value Handling -> Outlier Handling
    -> Encoding -> Scaling -> Normalization -> Feature Engineering
    -> Final Validation

Author: Senior ML / Python Engineering Team
Python: 3.11
"""

from __future__ import annotations

import logging
import warnings
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Optional

import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, RobustScaler, StandardScaler

# ======================================================================
# Safe import for FeatureBuilder (works both locally and in production)
# ======================================================================
try:
    from feature_builder import FeatureBuilder
except ImportError:
    from ..feature_engineering.feature_builder import FeatureBuilder


logger = logging.getLogger(__name__)
if not logger.handlers:
    _handler = logging.StreamHandler()
    _formatter = logging.Formatter(
        "%(asctime)s | %(levelname)s | %(name)s | %(message)s"
    )
    _handler.setFormatter(_formatter)
    logger.addHandler(_handler)
logger.setLevel(logging.INFO)


# ======================================================================
# SPEC-COMPLIANT PUBLIC INTERFACE (Required by Project Spec)
# ======================================================================

def remove_duplicates(df: pd.DataFrame) -> pd.DataFrame:
    """
    Remove duplicate rows from the DataFrame.

    Args:
        df: Input DataFrame.

    Returns:
        DataFrame with duplicate rows removed.
    """
    return df.drop_duplicates().reset_index(drop=True)


def handle_missing_values(df: pd.DataFrame, strategy: str = "median") -> pd.DataFrame:
    """
    Handle missing values using the specified strategy.

    Strategies:
        - 'mean': Fill numerical columns with mean, categorical with mode.
        - 'median': Fill numerical columns with median, categorical with mode.
        - 'mode': Fill all columns with mode.
        - 'drop': Drop rows containing any missing value.

    Args:
        df: Input DataFrame.
        strategy: Imputation strategy ('mean', 'median', 'mode', 'drop').

    Returns:
        DataFrame with missing values handled.

    Raises:
        ValueError: If an unsupported strategy is provided.
    """
    if strategy == "drop":
        return df.dropna().reset_index(drop=True)

    df_copy = df.copy()

    # Handle numerical columns
    numeric_cols = df_copy.select_dtypes(include=["number"]).columns
    for col in numeric_cols:
        if strategy == "mean":
            fill_val = df_copy[col].mean()
        elif strategy == "median":
            fill_val = df_copy[col].median()
        elif strategy == "mode":
            mode_vals = df_copy[col].mode()
            fill_val = mode_vals[0] if not mode_vals.empty else df_copy[col].median()
        else:
            raise ValueError(
                f"Unsupported strategy: '{strategy}'. "
                f"Choose from: mean, median, mode, drop"
            )
        df_copy[col] = df_copy[col].fillna(fill_val)

    # Handle categorical/text columns (always use mode)
    cat_cols = df_copy.select_dtypes(include=["object", "category", "string"]).columns
    for col in cat_cols:
        mode_vals = df_copy[col].mode()
        fill_val = mode_vals[0] if not mode_vals.empty else "unknown"
        df_copy[col] = df_copy[col].fillna(fill_val)

    return df_copy.reset_index(drop=True)


# ======================================================================
# Exceptions
# ======================================================================

class DataPreprocessingError(Exception):
    """Base exception for all preprocessing-related errors."""


class EmptyDatasetError(DataPreprocessingError):
    """Raised when the dataset is empty (no rows or no columns)."""


class DuplicateColumnError(DataPreprocessingError):
    """Raised when the dataset contains duplicate column names."""


class InvalidDatatypeError(DataPreprocessingError):
    """Raised when one or more columns hold unsupported data types."""


class InvalidDatetimeError(DataPreprocessingError):
    """Raised when a column expected to be datetime cannot be parsed."""


class InfiniteValueError(DataPreprocessingError):
    """Raised when numerical columns contain infinite values."""


class ConfigurationError(DataPreprocessingError):
    """Raised when an invalid configuration/strategy is supplied."""


# ======================================================================
# Enumerations for strategy configuration
# ======================================================================

class ImputationStrategy(str, Enum):
    """Supported strategies for missing value imputation."""

    MEAN = "mean"
    MEDIAN = "median"
    MODE = "mode"
    DROP_ROWS = "drop_rows"
    DROP_COLUMNS = "drop_columns"


class OutlierStrategy(str, Enum):
    """Supported strategies for outlier handling."""

    REMOVE = "remove"
    CAP = "cap"
    FLAG = "flag"


class ScalingStrategy(str, Enum):
    """Supported strategies for feature scaling."""

    STANDARD = "standard"
    MIN_MAX = "min_max"
    ROBUST = "robust"


class NormalizationStrategy(str, Enum):
    """Supported strategies for numerical normalization."""

    LOG = "log"
    SQRT = "sqrt"


# ======================================================================
# Configuration
# ======================================================================

@dataclass
class PreprocessingConfig:
    """
    Centralized, dataset-agnostic configuration for the preprocessing
    pipeline.
    """
    missing_value_threshold_drop_column: float = 0.5
    missing_value_threshold_drop_row: float = 0.05
    numerical_imputation_strategy: ImputationStrategy = ImputationStrategy.MEDIAN
    categorical_imputation_strategy: ImputationStrategy = ImputationStrategy.MODE
    outlier_strategy: OutlierStrategy = OutlierStrategy.CAP
    outlier_iqr_multiplier: float = 1.5
    scaling_strategy: ScalingStrategy = ScalingStrategy.STANDARD
    normalization_strategy: Optional[NormalizationStrategy] = NormalizationStrategy.LOG
    skewness_threshold: float = 1.0
    high_cardinality_threshold: int = 20
    constant_column_unique_threshold: int = 1
    rare_category_threshold: float = 0.01
    one_hot_max_categories: int = 20
    columns_to_exclude: list[str] = field(default_factory=list)
    random_state: int = 42


# ======================================================================
# Column type detection helper
# ======================================================================

class ColumnTypeDetector:
    """Detects numerical, categorical, datetime and boolean columns."""

    def __init__(self, config: PreprocessingConfig) -> None:
        self._config = config

    def _usable_columns(self, data_frame: pd.DataFrame) -> list[str]:
        return [
            column
            for column in data_frame.columns
            if column not in self._config.columns_to_exclude
        ]

    def detect_boolean_columns(self, data_frame: pd.DataFrame) -> list[str]:
        return [
            column
            for column in self._usable_columns(data_frame)
            if pd.api.types.is_bool_dtype(data_frame[column])
        ]

    def _is_string_datetime_column(self, series: pd.Series) -> bool:
        is_textual_dtype = pd.api.types.is_object_dtype(series) or pd.api.types.is_string_dtype(
            series
        )
        if not is_textual_dtype:
            return False

        non_null_values = series.dropna()
        if non_null_values.empty:
            return False

        sample_size = min(50, len(non_null_values))
        sample = non_null_values.sample(n=sample_size, random_state=42)
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", UserWarning)
            parsed = pd.to_datetime(sample, errors="coerce")
        return bool(parsed.notna().mean() >= 0.9)

    def detect_datetime_columns(self, data_frame: pd.DataFrame) -> list[str]:
        detected: list[str] = []
        for column in self._usable_columns(data_frame):
            series = data_frame[column]
            if pd.api.types.is_datetime64_any_dtype(series):
                detected.append(column)
            elif self._is_string_datetime_column(series):
                detected.append(column)
        return detected

    def detect_numerical_columns(self, data_frame: pd.DataFrame) -> list[str]:
        boolean_columns = set(self.detect_boolean_columns(data_frame))
        return [
            column
            for column in self._usable_columns(data_frame)
            if pd.api.types.is_numeric_dtype(data_frame[column])
            and column not in boolean_columns
        ]

    def detect_categorical_columns(self, data_frame: pd.DataFrame) -> list[str]:
        numerical_columns = set(self.detect_numerical_columns(data_frame))
        datetime_columns = set(self.detect_datetime_columns(data_frame))
        boolean_columns = set(self.detect_boolean_columns(data_frame))
        excluded = numerical_columns | datetime_columns | boolean_columns
        return [
            column
            for column in self._usable_columns(data_frame)
            if column not in excluded
        ]


# ======================================================================
# Validation
# ======================================================================

class DataValidator:
    """Performs structural and quality validation on a DataFrame."""

    def __init__(self, config: PreprocessingConfig) -> None:
        self._config = config
        self._type_detector = ColumnTypeDetector(config)

    def validate_not_empty(self, data_frame: pd.DataFrame) -> None:
        if data_frame.shape[0] == 0 or data_frame.shape[1] == 0:
            raise EmptyDatasetError(
                f"Dataset is empty: shape={data_frame.shape}."
            )

    def validate_unique_columns(self, data_frame: pd.DataFrame) -> None:
        duplicated = data_frame.columns[data_frame.columns.duplicated()].tolist()
        if duplicated:
            raise DuplicateColumnError(
                f"Duplicate column names found: {duplicated}."
            )

    def check_missing_values(self, data_frame: pd.DataFrame) -> pd.Series:
        missing_counts = data_frame.isnull().sum()
        return missing_counts[missing_counts > 0]

    def validate_datatypes(self, data_frame: pd.DataFrame) -> None:
        supported_kinds = {"b", "i", "u", "f", "c", "O", "M", "m"}
        invalid_columns = [
            column
            for column in data_frame.columns
            if data_frame[column].dtype.kind not in supported_kinds
        ]
        if invalid_columns:
            raise InvalidDatatypeError(
                f"Unsupported dtypes found in columns: {invalid_columns}."
            )

    def validate_datetime_columns(
        self, data_frame: pd.DataFrame, datetime_columns: Optional[list[str]] = None
    ) -> None:
        columns_to_check = (
            datetime_columns
            if datetime_columns is not None
            else self._type_detector.detect_datetime_columns(data_frame)
        )
        for column in columns_to_check:
            if column not in data_frame.columns:
                continue
            try:
                with warnings.catch_warnings():
                    warnings.simplefilter("ignore", UserWarning)
                    pd.to_datetime(data_frame[column], errors="raise")
            except (ValueError, TypeError) as error:
                raise InvalidDatetimeError(
                    f"Column '{column}' cannot be parsed as datetime: {error}"
                ) from error

    def validate_infinite_values(self, data_frame: pd.DataFrame) -> None:
        numerical_columns = self._type_detector.detect_numerical_columns(data_frame)
        if not numerical_columns:
            return
        numerical_data = data_frame[numerical_columns]
        has_infinite = np.isinf(numerical_data.to_numpy(dtype=float, na_value=0.0)).any()
        if has_infinite:
            affected = [
                column
                for column in numerical_columns
                if np.isinf(data_frame[column].to_numpy(dtype=float)).any()
            ]
            raise InfiniteValueError(
                f"Infinite values detected in columns: {affected}."
            )

    def detect_constant_columns(self, data_frame: pd.DataFrame) -> list[str]:
        return [
            column
            for column in data_frame.columns
            if data_frame[column].nunique(dropna=True)
            <= self._config.constant_column_unique_threshold
        ]

    def detect_high_cardinality_columns(self, data_frame: pd.DataFrame) -> list[str]:
        categorical_columns = self._type_detector.detect_categorical_columns(
            data_frame
        )
        return [
            column
            for column in categorical_columns
            if data_frame[column].nunique(dropna=True)
            > self._config.high_cardinality_threshold
        ]

    def run_initial_validation(self, data_frame: pd.DataFrame) -> None:
        logger.info("Running initial data validation.")
        self.validate_not_empty(data_frame)
        self.validate_unique_columns(data_frame)
        self.validate_datatypes(data_frame)

        missing_summary = self.check_missing_values(data_frame)
        if not missing_summary.empty:
            logger.info(
                "Missing values detected in %d column(s): %s",
                len(missing_summary),
                missing_summary.to_dict(),
            )

        constant_columns = self.detect_constant_columns(data_frame)
        if constant_columns:
            logger.warning("Constant columns detected: %s", constant_columns)

        high_cardinality_columns = self.detect_high_cardinality_columns(data_frame)
        if high_cardinality_columns:
            logger.warning(
                "High-cardinality columns detected: %s", high_cardinality_columns
            )

    def run_final_validation(self, data_frame: pd.DataFrame) -> None:
        logger.info("Running final data validation.")
        self.validate_not_empty(data_frame)
        self.validate_unique_columns(data_frame)
        self.validate_infinite_values(data_frame)

        remaining_missing = self.check_missing_values(data_frame)
        if not remaining_missing.empty:
            raise DataPreprocessingError(
                f"Final dataset still contains missing values: "
                f"{remaining_missing.to_dict()}."
            )


# ======================================================================
# Cleaning
# ======================================================================

class DataCleaner:
    """Performs structural cleaning operations on a DataFrame."""

    def remove_duplicate_rows(self, data_frame: pd.DataFrame) -> pd.DataFrame:
        duplicate_count = int(data_frame.duplicated().sum())
        if duplicate_count > 0:
            logger.info("Removing %d duplicate row(s).", duplicate_count)
            data_frame = data_frame.drop_duplicates().reset_index(drop=True)
        else:
            logger.info("No duplicate rows found.")
        return data_frame

    def standardize_column_names(self, data_frame: pd.DataFrame) -> pd.DataFrame:
        new_columns = (
            data_frame.columns.astype(str)
            .str.strip()
            .str.lower()
            .str.replace(r"[^0-9a-zA-Z]+", "_", regex=True)
            .str.strip("_")
        )
        data_frame = data_frame.copy()
        data_frame.columns = new_columns
        logger.info("Standardized column names.")
        return data_frame

    def standardize_string_values(self, data_frame: pd.DataFrame) -> pd.DataFrame:
        data_frame = data_frame.copy()
        textual_columns = [
            column
            for column in data_frame.columns
            if pd.api.types.is_object_dtype(data_frame[column])
            or pd.api.types.is_string_dtype(data_frame[column])
        ]
        for column in textual_columns:
            data_frame[column] = (
                data_frame[column]
                .apply(lambda value: value.strip() if isinstance(value, str) else value)
            )
        logger.info("Standardized string values in %d column(s).", len(textual_columns))
        return data_frame

    def remove_empty_rows(self, data_frame: pd.DataFrame) -> pd.DataFrame:
        before = data_frame.shape[0]
        data_frame = data_frame.dropna(axis=0, how="all").reset_index(drop=True)
        removed = before - data_frame.shape[0]
        if removed > 0:
            logger.info("Removed %d fully empty row(s).", removed)
        return data_frame

    def remove_empty_columns(self, data_frame: pd.DataFrame) -> pd.DataFrame:
        before_columns = set(data_frame.columns)
        data_frame = data_frame.dropna(axis=1, how="all")
        removed = before_columns - set(data_frame.columns)
        if removed:
            logger.info("Removed fully empty column(s): %s", sorted(removed))
        return data_frame

    def clean(self, data_frame: pd.DataFrame) -> pd.DataFrame:
        data_frame = self.standardize_column_names(data_frame)
        data_frame = self.remove_empty_rows(data_frame)
        data_frame = self.remove_empty_columns(data_frame)
        data_frame = self.remove_duplicate_rows(data_frame)
        data_frame = self.standardize_string_values(data_frame)
        return data_frame


# ======================================================================
# Missing value handling
# ======================================================================

class MissingValueHandler:
    """Analyzes and resolves missing values in a DataFrame."""

    def __init__(self, config: PreprocessingConfig) -> None:
        self._config = config
        self._type_detector = ColumnTypeDetector(config)

    def analyze_missing_values(self, data_frame: pd.DataFrame) -> pd.DataFrame:
        missing_count = data_frame.isnull().sum()
        missing_percentage = missing_count / len(data_frame)
        summary = pd.DataFrame(
            {
                "missing_count": missing_count,
                "missing_percentage": missing_percentage,
            }
        )
        summary = summary[summary["missing_count"] > 0]
        return summary.sort_values("missing_percentage", ascending=False)

    def _impute_numerical(
        self, data_frame: pd.DataFrame, column: str, strategy: ImputationStrategy
    ) -> None:
        if strategy == ImputationStrategy.MEAN:
            fill_value = data_frame[column].mean()
        elif strategy == ImputationStrategy.MEDIAN:
            fill_value = data_frame[column].median()
        else:
            raise ConfigurationError(
                f"Strategy '{strategy}' is not valid for numerical imputation."
            )
        data_frame[column] = data_frame[column].fillna(fill_value)

    def _impute_categorical(self, data_frame: pd.DataFrame, column: str) -> None:
        mode_values = data_frame[column].mode(dropna=True)
        fill_value = mode_values.iloc[0] if not mode_values.empty else "unknown"
        data_frame[column] = data_frame[column].fillna(fill_value)

    def handle_missing_values(self, data_frame: pd.DataFrame) -> pd.DataFrame:
        data_frame = data_frame.copy()
        summary = self.analyze_missing_values(data_frame)
        if summary.empty:
            logger.info("No missing values found.")
            return data_frame

        numerical_columns = set(self._type_detector.detect_numerical_columns(data_frame))
        columns_to_drop: list[str] = []

        for column, row in summary.iterrows():
            missing_fraction = row["missing_percentage"]

            if missing_fraction >= self._config.missing_value_threshold_drop_column:
                columns_to_drop.append(str(column))
                continue

            if missing_fraction < self._config.missing_value_threshold_drop_row:
                data_frame = data_frame.dropna(subset=[column])
                logger.info("Dropped rows with missing values in '%s'.", column)
                continue

            if column in numerical_columns:
                skewness = data_frame[column].skew()
                strategy = (
                    ImputationStrategy.MEDIAN
                    if abs(skewness) > self._config.skewness_threshold
                    else ImputationStrategy.MEAN
                )
                self._impute_numerical(data_frame, str(column), strategy)
                logger.info(
                    "Imputed numerical column '%s' using strategy '%s'.",
                    column,
                    strategy.value,
                )
            else:
                self._impute_categorical(data_frame, str(column))
                logger.info("Imputed categorical column '%s' using mode.", column)

        if columns_to_drop:
            data_frame = data_frame.drop(columns=columns_to_drop)
            logger.info(
                "Dropped column(s) exceeding missing threshold: %s",
                columns_to_drop,
            )

        return data_frame.reset_index(drop=True)


# ======================================================================
# Outlier handling
# ======================================================================

class OutlierHandler:
    """Detects and handles outliers in numerical columns using the IQR rule."""

    def __init__(self, config: PreprocessingConfig) -> None:
        self._config = config
        self._type_detector = ColumnTypeDetector(config)

    def compute_iqr_bounds(
        self, data_frame: pd.DataFrame, column: str
    ) -> tuple[float, float]:
        first_quartile = data_frame[column].quantile(0.25)
        third_quartile = data_frame[column].quantile(0.75)
        interquartile_range = third_quartile - first_quartile
        multiplier = self._config.outlier_iqr_multiplier
        lower_bound = first_quartile - multiplier * interquartile_range
        upper_bound = third_quartile + multiplier * interquartile_range
        return lower_bound, upper_bound

    def detect_outliers(
        self, data_frame: pd.DataFrame, column: str
    ) -> pd.Series:
        lower_bound, upper_bound = self.compute_iqr_bounds(data_frame, column)
        return (data_frame[column] < lower_bound) | (data_frame[column] > upper_bound)

    def remove_outliers(self, data_frame: pd.DataFrame, column: str) -> pd.DataFrame:
        mask = self.detect_outliers(data_frame, column)
        return data_frame.loc[~mask].reset_index(drop=True)

    def cap_outliers(self, data_frame: pd.DataFrame, column: str) -> pd.DataFrame:
        lower_bound, upper_bound = self.compute_iqr_bounds(data_frame, column)
        data_frame = data_frame.copy()
        data_frame[column] = data_frame[column].clip(lower=lower_bound, upper=upper_bound)
        return data_frame

    def flag_outliers(self, data_frame: pd.DataFrame, column: str) -> pd.DataFrame:
        data_frame = data_frame.copy()
        flag_column = f"{column}_is_outlier"
        data_frame[flag_column] = self.detect_outliers(data_frame, column)
        return data_frame

    def handle_outliers(
        self,
        data_frame: pd.DataFrame,
        strategy: Optional[OutlierStrategy] = None,
        columns: Optional[list[str]] = None,
    ) -> pd.DataFrame:
        strategy = strategy or self._config.outlier_strategy
        target_columns = columns or self._type_detector.detect_numerical_columns(
            data_frame
        )
        data_frame = data_frame.copy()

        for column in target_columns:
            outlier_count = int(self.detect_outliers(data_frame, column).sum())
            if outlier_count == 0:
                continue

            logger.info(
                "Found %d outlier(s) in column '%s'. Applying strategy '%s'.",
                outlier_count,
                column,
                strategy.value,
            )
            if strategy == OutlierStrategy.REMOVE:
                data_frame = self.remove_outliers(data_frame, column)
            elif strategy == OutlierStrategy.CAP:
                data_frame = self.cap_outliers(data_frame, column)
            elif strategy == OutlierStrategy.FLAG:
                data_frame = self.flag_outliers(data_frame, column)
            else:
                raise ConfigurationError(f"Unsupported outlier strategy: {strategy}")

        return data_frame.reset_index(drop=True)


# ======================================================================
# Encoding
# ======================================================================

class CategoricalEncoder:
    """Encodes categorical columns, safely handling high cardinality."""

    def __init__(self, config: PreprocessingConfig) -> None:
        self._config = config
        self._type_detector = ColumnTypeDetector(config)

    def detect_categorical_columns(self, data_frame: pd.DataFrame) -> list[str]:
        return self._type_detector.detect_categorical_columns(data_frame)

    def _group_high_cardinality_values(
        self, series: pd.Series, max_categories: int
    ) -> pd.Series:
        top_categories = series.value_counts().index[:max_categories]
        return series.where(series.isin(top_categories), other="other")

    def one_hot_encode(
        self, data_frame: pd.DataFrame, columns: Optional[list[str]] = None
    ) -> pd.DataFrame:
        data_frame = data_frame.copy()
        target_columns = columns or self.detect_categorical_columns(data_frame)
        if not target_columns:
            logger.info("No categorical columns to encode.")
            return data_frame

        for column in target_columns:
            unique_count = data_frame[column].nunique(dropna=True)
            if unique_count > self._config.one_hot_max_categories:
                logger.warning(
                    "Column '%s' has high cardinality (%d). "
                    "Grouping rare categories before encoding.",
                    column,
                    unique_count,
                )
                data_frame[column] = self._group_high_cardinality_values(
                    data_frame[column], self._config.one_hot_max_categories
                )

        encoded = pd.get_dummies(
            data_frame, columns=target_columns, prefix=target_columns, dummy_na=False
        )
        logger.info("One-hot encoded column(s): %s", target_columns)
        return encoded


# ======================================================================
# Scaling
# ======================================================================

class FeatureScaler:
    """Scales numerical columns using configurable scikit-learn scalers."""

    _SCALER_FACTORY = {
        ScalingStrategy.STANDARD: StandardScaler,
        ScalingStrategy.MIN_MAX: MinMaxScaler,
        ScalingStrategy.ROBUST: RobustScaler,
    }

    def __init__(self, config: PreprocessingConfig) -> None:
        self._config = config
        self._type_detector = ColumnTypeDetector(config)

    def scale(
        self,
        data_frame: pd.DataFrame,
        strategy: Optional[ScalingStrategy] = None,
        columns: Optional[list[str]] = None,
    ) -> pd.DataFrame:
        strategy = strategy or self._config.scaling_strategy
        target_columns = columns or self._type_detector.detect_numerical_columns(
            data_frame
        )
        if not target_columns:
            logger.info("No numerical columns to scale.")
            return data_frame

        scaler_class = self._SCALER_FACTORY.get(strategy)
        if scaler_class is None:
            raise ConfigurationError(f"Unsupported scaling strategy: {strategy}")

        data_frame = data_frame.copy()
        scaler = scaler_class()
        data_frame[target_columns] = scaler.fit_transform(data_frame[target_columns])
        logger.info(
            "Scaled column(s) %s using strategy '%s'.", target_columns, strategy.value
        )
        return data_frame


# ======================================================================
# Normalization
# ======================================================================

class Normalizer:
    """Applies variance-stabilizing transformations to skewed numerical data."""

    def __init__(self, config: PreprocessingConfig) -> None:
        self._config = config
        self._type_detector = ColumnTypeDetector(config)

    def log_transform(self, data_frame: pd.DataFrame, column: str) -> pd.DataFrame:
        data_frame = data_frame.copy()
        minimum_value = data_frame[column].min()
        shift = abs(minimum_value) + 1.0 if minimum_value < 0 else 0.0
        data_frame[column] = np.log1p(data_frame[column] + shift)
        return data_frame

    def sqrt_transform(self, data_frame: pd.DataFrame, column: str) -> pd.DataFrame:
        data_frame = data_frame.copy()
        minimum_value = data_frame[column].min()
        shift = abs(minimum_value) if minimum_value < 0 else 0.0
        data_frame[column] = np.sqrt(data_frame[column] + shift)
        return data_frame

    def normalize(
        self,
        data_frame: pd.DataFrame,
        strategy: Optional[NormalizationStrategy] = None,
        columns: Optional[list[str]] = None,
    ) -> pd.DataFrame:
        strategy = strategy or self._config.normalization_strategy
        if strategy is None:
            logger.info("Normalization disabled by configuration.")
            return data_frame

        target_columns = columns or self._type_detector.detect_numerical_columns(
            data_frame
        )
        data_frame = data_frame.copy()

        for column in target_columns:
            skewness = data_frame[column].skew()
            if abs(skewness) <= self._config.skewness_threshold:
                continue

            logger.info(
                "Normalizing skewed column '%s' (skew=%.3f) using '%s'.",
                column,
                skewness,
                strategy.value,
            )
            if strategy == NormalizationStrategy.LOG:
                data_frame = self.log_transform(data_frame, column)
            elif strategy == NormalizationStrategy.SQRT:
                data_frame = self.sqrt_transform(data_frame, column)
            else:
                raise ConfigurationError(f"Unsupported normalization strategy: {strategy}")

        return data_frame


# ======================================================================
# Preprocessing pipeline orchestrator
# ======================================================================

class PreprocessingPipeline:
    """
    Orchestrates the complete, generic preprocessing pipeline for any
    tabular dataset.
    """

    def __init__(self, config: Optional[PreprocessingConfig] = None) -> None:
        self._config = config or PreprocessingConfig()
        self._validator = DataValidator(self._config)
        self._cleaner = DataCleaner()
        self._missing_value_handler = MissingValueHandler(self._config)
        self._outlier_handler = OutlierHandler(self._config)
        self._encoder = CategoricalEncoder(self._config)
        self._scaler = FeatureScaler(self._config)
        self._normalizer = Normalizer(self._config)
        self._feature_builder = FeatureBuilder(
            rare_category_threshold=self._config.rare_category_threshold
        )

    def run(self, data_frame: pd.DataFrame) -> pd.DataFrame:
        logger.info("Starting preprocessing pipeline. Input shape: %s", data_frame.shape)

        self._validator.run_initial_validation(data_frame)

        data_frame = self._cleaner.clean(data_frame)
        logger.info("Cleaning complete. Shape: %s", data_frame.shape)

        data_frame = self._missing_value_handler.handle_missing_values(data_frame)
        logger.info("Missing value handling complete. Shape: %s", data_frame.shape)

        data_frame = self._outlier_handler.handle_outliers(data_frame)
        logger.info("Outlier handling complete. Shape: %s", data_frame.shape)

        data_frame = self._encoder.one_hot_encode(data_frame)
        logger.info("Encoding complete. Shape: %s", data_frame.shape)

        data_frame = self._scaler.scale(data_frame)
        logger.info("Scaling complete. Shape: %s", data_frame.shape)

        data_frame = self._normalizer.normalize(data_frame)
        logger.info("Normalization complete. Shape: %s", data_frame.shape)

        data_frame = self._feature_builder.build_features(data_frame)
        logger.info("Feature engineering complete. Shape: %s", data_frame.shape)

        self._validator.run_final_validation(data_frame)
        logger.info("Preprocessing pipeline finished. Output shape: %s", data_frame.shape)

        return data_frame


def build_ml_ready_dataset(
    data_frame: pd.DataFrame, config: Optional[PreprocessingConfig] = None
) -> pd.DataFrame:
    pipeline = PreprocessingPipeline(config=config)
    return pipeline.run(data_frame)
