# -*- coding: utf-8 -*-
"""feature_builder.py29/7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hjn4pHAI3QiwBRiOOXP2xhKpAtonUVUQ
"""

"""
feature_builder.py

Generic, production-ready feature engineering component for tabular
datasets.

Implements the `FeatureBuilder` class, responsible for:
    - Automatic datetime column detection.
    - Calendar feature extraction (year, month, day, day of week,
      quarter, weekend flag).
    - Rare category grouping for categorical columns, when appropriate.
    - One-Hot Encoding for categorical features.

Author: Senior ML / Python Engineering Team
Python: 3.11
"""

from __future__ import annotations

import logging
import warnings
from typing import Optional

import pandas as pd


logger = logging.getLogger(__name__)
if not logger.handlers:
    _handler = logging.StreamHandler()
    _formatter = logging.Formatter(
        "%(asctime)s | %(levelname)s | %(name)s | %(message)s"
    )
    _handler.setFormatter(_formatter)
    logger.addHandler(_handler)
logger.setLevel(logging.INFO)


# ======================================================================
# SPEC-COMPLIANT PUBLIC INTERFACE (Convenience functions)
# ======================================================================

def extract_datetime_features(df: pd.DataFrame, column: str, drop_original: bool = True) -> pd.DataFrame:
    """
    Extract calendar features from a datetime column.

    Args:
        df: Input DataFrame.
        column: Name of the datetime column.
        drop_original: Whether to drop the original column.

    Returns:
        DataFrame with extracted datetime features.
    """
    builder = FeatureBuilder(drop_original_datetime_columns=drop_original)
    return builder.extract_datetime_features(df, column)


def group_rare_categories(df: pd.DataFrame, column: str, threshold: float = 0.01) -> pd.DataFrame:
    """
    Group rare categories in a categorical column into a single bucket.

    Args:
        df: Input DataFrame.
        column: Name of the categorical column.
        threshold: Frequency below which categories are considered rare.

    Returns:
        DataFrame with rare categories grouped.
    """
    builder = FeatureBuilder(rare_category_threshold=threshold)
    return builder.group_rare_categories(df, column)


def encode_categorical_features(df: pd.DataFrame, columns: Optional[list[str]] = None) -> pd.DataFrame:
    """
    Apply One-Hot Encoding to categorical columns.
    
    Args:
        df: Input DataFrame.
        columns: List of columns to encode (auto-detects if None).
        
    Returns:
        DataFrame with one-hot encoded columns.
    """
    builder = FeatureBuilder()
    return builder.one_hot_encode(df, columns)


# ======================================================================
# Datetime Column Detector
# ======================================================================

class DatetimeColumnDetector:
    """Detects columns that represent dates or timestamps."""

    def __init__(self, parse_sample_size: int = 100, min_parse_ratio: float = 0.9) -> None:
        self._parse_sample_size = parse_sample_size
        self._min_parse_ratio = min_parse_ratio

    def _is_parseable_as_datetime(self, series: pd.Series) -> bool:
        non_null_values = series.dropna()
        if non_null_values.empty:
            return False

        sample = non_null_values.sample(
            n=min(self._parse_sample_size, len(non_null_values)),
            random_state=42,
        )
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", UserWarning)
            parsed = pd.to_datetime(sample, errors="coerce")
        success_ratio = parsed.notna().mean()
        return bool(success_ratio >= self._min_parse_ratio)

    def detect(self, data_frame: pd.DataFrame) -> list[str]:
        detected_columns: list[str] = []

        for column in data_frame.columns:
            series = data_frame[column]

            if pd.api.types.is_datetime64_any_dtype(series):
                detected_columns.append(column)
                continue

            is_textual_dtype = pd.api.types.is_object_dtype(
                series
            ) or pd.api.types.is_string_dtype(series)
            if is_textual_dtype and self._is_parseable_as_datetime(series):
                detected_columns.append(column)

        return detected_columns


# ======================================================================
# Feature Builder
# ======================================================================

class FeatureBuilder:
    """
    Builds derived features from raw tabular data, in a fully generic and
    dataset-agnostic manner.
    """

    def __init__(
        self,
        rare_category_threshold: float = 0.01,
        rare_category_label: str = "rare",
        rare_category_min_unique: int = 10,
        drop_original_datetime_columns: bool = True,
    ) -> None:
        self._rare_category_threshold = rare_category_threshold
        self._rare_category_label = rare_category_label
        self._rare_category_min_unique = rare_category_min_unique
        self._drop_original_datetime_columns = drop_original_datetime_columns
        self._datetime_detector = DatetimeColumnDetector()

    def detect_datetime_columns(self, data_frame: pd.DataFrame) -> list[str]:
        return self._datetime_detector.detect(data_frame)

    def _to_datetime(self, series: pd.Series) -> pd.Series:
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", UserWarning)
            return pd.to_datetime(series, errors="coerce")

    def extract_year(self, data_frame: pd.DataFrame, column: str) -> pd.DataFrame:
        data_frame = data_frame.copy()
        data_frame[f"{column}_year"] = self._to_datetime(data_frame[column]).dt.year
        return data_frame

    def extract_month(self, data_frame: pd.DataFrame, column: str) -> pd.DataFrame:
        data_frame = data_frame.copy()
        data_frame[f"{column}_month"] = self._to_datetime(data_frame[column]).dt.month
        return data_frame

    def extract_day(self, data_frame: pd.DataFrame, column: str) -> pd.DataFrame:
        data_frame = data_frame.copy()
        data_frame[f"{column}_day"] = self._to_datetime(data_frame[column]).dt.day
        return data_frame

    def extract_day_of_week(self, data_frame: pd.DataFrame, column: str) -> pd.DataFrame:
        data_frame = data_frame.copy()
        data_frame[f"{column}_day_of_week"] = self._to_datetime(
            data_frame[column]
        ).dt.dayofweek
        return data_frame

    def extract_quarter(self, data_frame: pd.DataFrame, column: str) -> pd.DataFrame:
        data_frame = data_frame.copy()
        data_frame[f"{column}_quarter"] = self._to_datetime(data_frame[column]).dt.quarter
        return data_frame

    def extract_is_weekend(self, data_frame: pd.DataFrame, column: str) -> pd.DataFrame:
        data_frame = data_frame.copy()
        day_of_week = self._to_datetime(data_frame[column]).dt.dayofweek
        data_frame[f"{column}_is_weekend"] = day_of_week.isin([5, 6])
        return data_frame

    def extract_datetime_features(
        self, data_frame: pd.DataFrame, column: str
    ) -> pd.DataFrame:
        if column not in data_frame.columns:
            raise KeyError(f"Column '{column}' does not exist in the provided DataFrame.")

        data_frame = self.extract_year(data_frame, column)
        data_frame = self.extract_month(data_frame, column)
        data_frame = self.extract_day(data_frame, column)
        data_frame = self.extract_day_of_week(data_frame, column)
        data_frame = self.extract_quarter(data_frame, column)
        data_frame = self.extract_is_weekend(data_frame, column)

        if self._drop_original_datetime_columns:
            data_frame = data_frame.drop(columns=[column])

        logger.info("Extracted calendar features from datetime column '%s'.", column)
        return data_frame

    def group_rare_categories(self, data_frame: pd.DataFrame, column: str) -> pd.DataFrame:
        if column not in data_frame.columns:
            raise KeyError(f"Column '{column}' does not exist in the provided DataFrame.")

        unique_count = data_frame[column].nunique(dropna=True)
        if unique_count < self._rare_category_min_unique:
            return data_frame
