"""Shared LangGraph state definition for the AutoAnalyst AI multi-agent system.

Every agent node receives and returns an instance of ``AutoAnalystState``.
Fields are ``total=False`` so each node only needs to populate the keys it
owns — missing keys are treated as ``None`` / empty by downstream nodes.

Ownership map
─────────────
``df``                → Dataset Intake Agent  (Team 2)
``cleaned_df``        → Preprocessing / Cleaning Agent  (Team 4)
``profile``           → Profiling Agent  (Team 2)
``eda_results``       → EDA Agent  (Team 3)
``target_column``     → set by user / Orchestrator  (Team 1)
``model_results``     → **Modeling Agent (Team 5)**
``evaluation_results``→ Evaluation Agent  (Team 6)
``insights``          → Insight Agent  (Team 6)
``report_path``       → Report Agent  (Team 7)
``errors``            → any agent that catches an exception
``warnings``          → any agent that detects a non-fatal issue
"""

from __future__ import annotations

from typing import Any, TypedDict

import pandas as pd


class AutoAnalystState(TypedDict, total=False):
    """Shared pipeline state passed between every agent node."""

    # ── Input / loading ──────────────────────────────────────────────────────
    dataset_path: str
    """Absolute path to the raw data file (CSV or Excel)."""

    df: pd.DataFrame
    """Raw DataFrame loaded by the Dataset Intake Agent."""

    # ── Profiling ─────────────────────────────────────────────────────────────
    profile: dict[str, Any]
    """High-level dataset statistics (rows, columns, missing totals …)."""

    missing_values_report: pd.DataFrame
    """Per-column missing-value counts and percentages."""

    # ── EDA ───────────────────────────────────────────────────────────────────
    eda_results: dict[str, Any]
    """Numeric summaries, correlation matrix, and chart metadata."""

    # ── Preprocessing / feature engineering ──────────────────────────────────
    cleaned_df: pd.DataFrame
    """Cleaned, encoded, scaled, model-ready DataFrame."""

    cleaning_log: list[str]
    """Human-readable log of every transformation applied."""

    feature_columns: list[str]
    """Ordered list of feature column names used for modelling."""

    # ── Modelling (Team 5 writes these) ───────────────────────────────────────
    target_column: str | None
    """Name of the target column; ``None`` triggers clustering mode."""

    model_results: dict[str, Any] | None
    """
    Structured output populated by the Modeling Agent.

    Schema
    ──────
    {
        "task_type": "classification" | "regression" | "clustering",
        "algorithm_used": str,
        "hyperparameters": dict,
        "train_rows": int,
        "test_rows": int,
        "predictions": list,          # y_pred on test split
        "y_test": list,               # y_true for test split
        "cluster_assignments": list,  # only for clustering tasks
        "feature_importances": dict,  # col → importance, if available
        "model_file": str | None,     # path to serialised estimator
        "comparison": list[dict],     # multi-model comparison table
        "decision_log": list[str],    # why this algo was chosen
    }
    """

    # ── Evaluation (Team 6 writes these) ─────────────────────────────────────
    evaluation_results: dict[str, Any] | None
    """Performance metrics returned by the Evaluation Agent."""

    # ── Insights & reporting ─────────────────────────────────────────────────
    insights: list[str]
    """Human-readable insight bullets generated by the Insight Agent."""

    report_path: str
    """Absolute path to the generated Markdown / HTML report."""

    # ── Diagnostics ───────────────────────────────────────────────────────────
    errors: list[str]
    """Fatal errors collected by any agent node."""

    warnings: list[str]
    """Non-fatal warnings collected by any agent node."""
