"""Tool Layer registry and exports for AutoAnalyst AI."""

from __future__ import annotations

from autoanalyst.tools.base import BaseAnalyticalTool, ToolMetadata, ToolResult
from autoanalyst.tools.data_tools import (
    LoadDatasetInput,
    LoadDatasetOutput,
    LoadDatasetTool,
    PreviewDatasetInput,
    PreviewDatasetOutput,
    PreviewDatasetTool,
)
from autoanalyst.tools.eda_tools import (
    CorrelationAnalysisTool,
    CorrelationInput,
    CorrelationOutput,
    DistributionAnalysisTool,
    DistributionInput,
    DistributionOutput,
    OutlierDetectionInput,
    OutlierDetectionOutput,
    OutlierDetectionTool,
)
from autoanalyst.tools.evaluation_tools import (
    EvaluateModelInput,
    EvaluateModelOutput,
    EvaluateModelTool,
    PermutationImportanceInput,
    PermutationImportanceOutput,
    PermutationImportanceTool,
)
from autoanalyst.tools.ml_tools import (
    BenchmarkModelsInput,
    BenchmarkModelsOutput,
    BenchmarkModelsTool,
    InferMLTaskInput,
    InferMLTaskOutput,
    InferMLTaskTool,
)
from autoanalyst.tools.preprocessing_tools import (
    EncodeFeaturesInput,
    EncodeFeaturesOutput,
    EncodeFeaturesTool,
    ExecuteCleaningInput,
    ExecuteCleaningOutput,
    ExecuteCleaningTool,
    GenerateTransformationPlanTool,
    PlannedAction,
    TransformationPlanInput,
    TransformationPlanOutput,
)
from autoanalyst.tools.profiling_tools import (
    MissingnessReportInput,
    MissingnessReportOutput,
    MissingnessReportTool,
    ProfileDatasetInput,
    ProfileDatasetOutput,
    ProfileDatasetTool,
)
from autoanalyst.tools.reporting_tools import (
    CompileReportInput,
    CompileReportOutput,
    CompileReportTool,
    DetectDriftInput,
    DetectDriftOutput,
    DetectDriftTool,
)

ALL_ANALYTICAL_TOOLS = [
    LoadDatasetTool(),
    PreviewDatasetTool(),
    ProfileDatasetTool(),
    MissingnessReportTool(),
    CorrelationAnalysisTool(),
    DistributionAnalysisTool(),
    OutlierDetectionTool(),
    GenerateTransformationPlanTool(),
    ExecuteCleaningTool(),
    EncodeFeaturesTool(),
    InferMLTaskTool(),
    BenchmarkModelsTool(),
    EvaluateModelTool(),
    PermutationImportanceTool(),
    CompileReportTool(),
    DetectDriftTool(),
]

__all__ = [
    "ALL_ANALYTICAL_TOOLS",
    "BaseAnalyticalTool",
    "BenchmarkModelsInput",
    "BenchmarkModelsOutput",
    "BenchmarkModelsTool",
    "CompileReportInput",
    "CompileReportOutput",
    "CompileReportTool",
    "CorrelationAnalysisTool",
    "CorrelationInput",
    "CorrelationOutput",
    "DetectDriftInput",
    "DetectDriftOutput",
    "DetectDriftTool",
    "DistributionAnalysisTool",
    "DistributionInput",
    "DistributionOutput",
    "EncodeFeaturesInput",
    "EncodeFeaturesOutput",
    "EncodeFeaturesTool",
    "EvaluateModelInput",
    "EvaluateModelOutput",
    "EvaluateModelTool",
    "ExecuteCleaningInput",
    "ExecuteCleaningOutput",
    "ExecuteCleaningTool",
    "GenerateTransformationPlanTool",
    "InferMLTaskInput",
    "InferMLTaskOutput",
    "InferMLTaskTool",
    "LoadDatasetInput",
    "LoadDatasetOutput",
    "LoadDatasetTool",
    "MissingnessReportInput",
    "MissingnessReportOutput",
    "MissingnessReportTool",
    "OutlierDetectionInput",
    "OutlierDetectionOutput",
    "OutlierDetectionTool",
    "PermutationImportanceInput",
    "PermutationImportanceOutput",
    "PermutationImportanceTool",
    "PlannedAction",
    "PreviewDatasetInput",
    "PreviewDatasetOutput",
    "PreviewDatasetTool",
    "ProfileDatasetInput",
    "ProfileDatasetOutput",
    "ProfileDatasetTool",
    "ToolMetadata",
    "ToolResult",
    "TransformationPlanInput",
    "TransformationPlanOutput",
]
