"""Package campaign outputs into a downloadable ZIP archive."""

from __future__ import annotations

import io
import json
import zipfile
from typing import Any, Dict, Optional


class AssetPackager:
    """Package campaign outputs into a downloadable ZIP archive."""

    @staticmethod
    def package_campaign(
        campaign_id: str,
        content: Optional[Dict[str, Any]] = None,
    ) -> io.BytesIO:
        """Create an in-memory ZIP containing campaign assets.

        Parameters
        ----------
        campaign_id:
            Unique campaign identifier used in file naming.
        content:
            Frontend-shaped content dict (ads, emailSequences, socialPosts, summary).

        Returns
        -------
        io.BytesIO
            Seeked-to-zero buffer ready for streaming.
        """
        buffer = io.BytesIO()
        with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zf:
            # Campaign metadata
            meta = {"campaign_id": campaign_id, "package_version": "1.0"}
            zf.writestr("campaign_meta.json", json.dumps(meta, indent=2))

            # Content assets
            if content:
                zf.writestr("content/full_content.json", json.dumps(content, indent=2))

                if "ads" in content:
                    zf.writestr("content/ads.json", json.dumps(content["ads"], indent=2))
                if "emailSequences" in content:
                    zf.writestr(
                        "content/email_sequences.json",
                        json.dumps(content["emailSequences"], indent=2),
                    )
                if "socialPosts" in content:
                    zf.writestr(
                        "content/social_posts.json",
                        json.dumps(content["socialPosts"], indent=2),
                    )
                if "summary" in content:
                    zf.writestr("campaign_summary.txt", content["summary"])

            # README
            readme = (
                f"# Campaign Assets — {campaign_id}\n\n"
                "Generated by AdPilot.\n\n"
                "## Contents\n"
                "- campaign_meta.json — Package metadata\n"
                "- content/ — All generated campaign content\n"
                "- campaign_summary.txt — Executive summary\n"
            )
            zf.writestr("README.md", readme)

        buffer.seek(0)
        return buffer
